[workspace]
authors = [
    "promit_search <ian.herzogpohl@gmail.com>",
]
channels = ["conda-forge", "bioconda"]
name = "promit_search"
description = "test"
platforms = ["win-64", "linux-64",  "osx-64"]
version = "0.0.0"
license = "Apache-2.0"
readme = "README.md"
preview = ["pixi-build"]

[environments]
dev = ["dev"]
docs = ["docs"]
pharmit = { features = ["pharmit"], no-default-feature = true }
logs-pred = { features = ["logs-pred"], no-default-feature = true }

[tasks]

[pypi-dependencies]
promit_search = { path = ".", editable = true }
gypsum-dl = ">=1.2.7, <2"

[dependencies]
python = "=3.12"
prolif = ">=2.1.0,<3"
rdkit = ">=2026.3.3,<2027"
numpy = ">=2.5.0,<3"
scipy = ">=1.18.0,<2"
mpi4py = ">=4.1.2,<5"
molvs = ">=0.1.1,<0.2"
requests = ">=2.34.2,<3"

[target.linux-64.dependencies]
reduce = ">=4.15,<5"


[feature.logs-pred]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-64"]

[feature.logs-pred.pypi-dependencies]
promit_search = { path = ".", editable = true }

[feature.logs-pred.dependencies]
python = "==3.7.6"
aqsolpred_web = { git = "https://github.com/nacefguessaymi/AqSolPred-web.git" }


[feature.pharmit.target.linux-64.dependencies]
pharmit = { url = "https://github.com/durrantlab/pharmit-dl/releases/download/v0.1.3/pharmit-0.1.3-h41f06ac_0.conda" }

[feature.pharmit]
channels = ["conda-forge"]
platforms = ["linux-64"]


[feature.dev.dependencies]
black = ">=23.10.0"
isort = ">=5.12.0"
pylint = ">=3.0.1"
mypy = ">=1.6.0"
pytest = ">=7.4.2"
pytest-cov = ">=4.1.0"
coverage = ">=7.3.1"
pytest-html = ">=4.0.1"
colorama = ">=0.4.6"

[feature.dev.tasks]
mdlint = { cmd = ["markdownlint-cli2", '"**/*.{md,markdown}"', "--fix", "--config", ".markdownlint.yaml", "||", "true"] }
isort = { cmd = ["isort", "--settings-path", ".isort.cfg", "./study", "./tests", "./promit_search", "||", "true"] }
black = { cmd = ["black", "--config", ".black.toml", "./study", "./tests", "./promit_search", "||", "true"] }
format = { depends-on = ["mdlint", "isort", "black"] }
tests = { cmd = [
    "PYTHONPATH=.",
    "pytest",
    "-c",
    ".pytest.ini",
    "--cov='promit_search'",
    "--cov-report=xml",
    "--junit-xml=report.xml",
    "--failed-first",
]}
coverage = { cmd = ["coverage", "report"] }
cleanup-build = { cmd = ["rm", "-rf", "./build"] }
build = { cmd = ["python3", "-m", "build"], depends-on = ["cleanup-build"]}
publish-test = { cmd = ["twine", "upload", "--repository", "testpypi", "dist/*"] }
publish = { cmd = ["twine", "upload", "dist/*"] }

[feature.dev.pypi-dependencies]
build = ">=1.2.2.post1,<2"
mypy-extensions = ">=1.0.0"

[feature.docs.dependencies]
mkdocs = ">=1.6.1,<2"
mkdocs-material = ">=9.5.44,<10"
pymdown-extensions = ">=10.12,<11"
mkdocs-table-reader-plugin = ">=3.1.0,<4"
mkdocstrings = ">=0.26.2,<0.27"
mkdocstrings-python = ">=1.12.2,<2"
mkdocs-gen-files = ">=0.4.0,<0.5"
mkdocs-macros-plugin = ">=1.3.7,<2"
mkdocs-jupyter = ">=0.25.0,<0.26"
mkdocs-glightbox = ">=0.4.0,<0.5"
mkdocs-git-revision-date-localized-plugin = ">=1.2.9,<2"

[feature.docs.pypi-dependencies]
material-plausible-plugin = ">=0.2.0,<0.3"
mkdocs-print-site-plugin = ">=2.6.0,<3"
mkdocs-awesome-nav = ">=3.0.0, <4"

[feature.docs.tasks]
docs = { cmd = ["rm", "-rf", "./public/", "&&", "mkdocs", "build", "-d", "public/"], env = {NO_MKDOCS_2_WARNING = "1"} }
serve = { cmd = ["mkdocs", "serve"] , env = {NO_MKDOCS_2_WARNING = "1"}}
