from pathlib import Path 
import prolif as plf

from promit_search.io import gen
from .find_interactions import find_interactions

def enable_pharms(sdf_file: Path, json_file: Path, protein_mol: plf.Molecule, 
                  prolif_settings: dict, op_path: Path):
    """Takes in SDF / pharmacophore pair, validates the pharmacophores
    using the itneraction fingerprint generated by prolif, disables
    all non-interacting pharmacophores, and prints the new json

    Args:
        sdf_file: the molecule whose pharmacophores are being checked
            Already fully validated
        json_file: the pharmacophore list
            Already fully validated
        protein_path: the protein as prolif molecule
            Already fully validated
        prolif_settings: settings to edit prolif
        op_path: where final JSON will be placed
    """
    # check if op_path exists already
    gen.file_exist_warn(op_path)
    # find all interactions between molecule and protein
    inter_dict: dict[str, list[int]] = find_interactions(sdf_file, protein_mol, prolif_settings)
    
